---
title: "schul_swd"
author: "PM"
date: "`r Sys.Date()`"
header-includes:
   - \usepackage{amsmath}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(SteppedPower)
```

## Vorgedanken
Schulfehltage $s_h$ im Halbjahr $h$ darstellbar als Summe der 
$j_{ih}$, Fehltage der Jahrgaenge $i$ im Halbjahr $h$.
Dabei entspricht $i \in \{1,\ldots,5\}$ dem Jahrgang im zweiten Studienjahr, und 
$h \in \{1,\ldots,4\}$ den Halbjahren ab Studienbeginn.
$$
\underbrace{\left(\begin{array}{c}
s_1 \\ s_2 \\ s_3 \\ s_4 
\end{array}\right)}_{=:S} =
\underbrace{\left(\begin{array}{cccccccccccccccc}
0 &0& 1 &0&0&0& 1 &0&0&0& 1 &0&0&0& 1 &0\\
0 &0&0& 1 &0&0&0& 1 &0&0&0& 1 &0&0&0& 1 \\
1 &0&0&0& 1 &0&0&0& 1 &0&0&0& 1 &0&0&0\\
0 & 1 &0&0&0& 1 &0&0&0& 1 &0&0&0& 1 &0&0
\end{array}\right)}_\textrm{=:X}
\cdot
\underbrace{\begin{pmatrix}
j_{13}\\j_{14}\\j_{21}\\j_{22}\\j_{23}\\j_{24}\\j_{31}\\j_{32}\\j_{33}\\j_{34}\\
j_{41}\\j_{42}\\j_{43}\\j_{44}\\j_{51}\\j_{52}
\end{pmatrix}
}_\textrm{=:J}
$$

## Kovarianz von $J$ (in random-effects-Denkweise)

Gesamtvarianz auf Ebene Jahrgang pro Halbjahr laesst sich zerlegen in:

* $\Sigma_0$ := Schuleffekt (ein "random intercept" auf Clusterebene)
* $\Sigma_1$ := Jahrgangseffekt (d.h. Kohorteneffekt)
* $\Sigma_2$ := Intra-Schuljahrseffekt (?) (denkbar, aber ich weiss nicht genau, wie ich mir den vorstellen sollte..)
* $\Sigma_3$ := residuelle Varianz

Schul- und Jahrgangseffekt sollten sich aus ikids am ehesten schaetzen lassen, diese erscheinen mir auch als die sinnigsten ...

$\text{Cov}(J)=$
$$
\left(\begin{smallmatrix}
\Sigma_0 + \Sigma_1 + \Sigma_3 &\Sigma_0+ \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0&\Sigma_0\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1 + \Sigma_3&\Sigma_0 + \Sigma_1\\
\Sigma_0 &\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0&\Sigma_0 + \Sigma_1&\Sigma_0 + \Sigma_1 + \Sigma_3
\end{smallmatrix}\right)
$$

## Kovarianz von $S$
Die Kovarianzmatrix zu einem Cluster (also auf Schulebene) saehe dann so aus:
$$
\text{Cov}(S)= X \,\, \text{Cov}(J) \,\, X' =
\left(\begin{array}{cccc}
16\Sigma_0+4\Sigma_1+4\Sigma_3 & 16\Sigma_0+4\Sigma_1 & 16\Sigma_0+3\Sigma_1& 16\Sigma_0+3\Sigma_1\\
16\Sigma_0+4\Sigma_1 & 16\Sigma_0+4\Sigma_1+4\Sigma_3 & 16\Sigma_0+3\Sigma_1& 16\Sigma_0+3\Sigma_1\\
16\Sigma_0+3\Sigma_1& 16\Sigma_0+3\Sigma_1& 16\Sigma_0+4\Sigma_1+4\Sigma_3 & 16\Sigma_0+4\Sigma_1 \\
16\Sigma_0+3\Sigma_1& 16\Sigma_0+3\Sigma_1& 16\Sigma_0+4\Sigma_1 & 16\Sigma_0+4\Sigma_1+4\Sigma_3 \\
\end{array}\right)
$$
Sieht sogar noch verhaeltnismaessig brav aus. Was denkst du?


p.s. `SteppedPower` koennte mit so einer Kovarianzstruktur - allerdings recht unelegant - umgehen :) 

<!-- ## power in wlsMixed -->
<!-- ```{r} -->
<!-- Sig0 <- .1  -->
<!-- Sig1 <- .2 -->
<!-- Sig3 <- .2 -->

<!-- CovBlk1 <- matrix(16*Sig0+4*Sig1,nrow=2,ncol=2) -->
<!-- CovBlk2 <- matrix(16*Sig0+3*Sig1,nrow=2,ncol=2) -->

<!-- CovBlk <- cbind(rbind(CovBlk1,CovBlk2),rbind(CovBlk2,CovBlk1)) -->
<!-- diag(CovBlk) <- diag(CovBlk)+4*Sig3 -->

<!-- wlsMixedPower(Cl=c(3,3,3), EffSize=.5, sigma=1,tau=1,CovBlk=CovBlk) -->
<!-- ``` -->



