---
title: "TODO"
author: "PM"
date: "19 Januar 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# general

* Nicer names needed !!
* New wrapper that interprets timepoints as individuals (for non-longitutinal settings)

## compare_designs

* add non-normal outcomes

## wlsMixedPower

* options to adjust for degrees of freedom (between-within, containment, none, ... )
* rewrite the very heart of the calculation as a function in sigma (using optim or similar)
* add random trt eff. Possibly just by manipulating vector tau.

* uniroot prduces error if max N_range doesnt reach target power. More informative feedback needed. **DONE**

* for samp size: think about what really needs to be kept constant and what should be able to vary (eg icc and tau)

## optFunction

* does not work for parallel designs! but why ??  **done**

## non-normal-wrapper

* add design selection option **DONE**

* doesn't work for time_adjust=none (!!)
* doesn't work for parallel_baseline. But why? ... passing of timepoints !

## construct_CovMat

  * should it return a list of three elements?
    * matrix
    * timepoints
    * SumCl
  * NAMING THINGS IS HARD !! 
  
  * other options for time_adjust: "linear", "periodic", 

## simulation

  * dependencies aufraeumen
    * MATRIX and stats both? maybe load only needed functions?
    * what about `car` ? needed only for `logit()`?
  * normal case ? 
  * poisson ?
  * cohort studies



## TALKING POINTS for ISCB

* advise to use rand trt effect in literature (Hughes 2015 Thompson 2017 ... )
* inflated test size (esp. for smaller number of clusters)
* try to find balance 
* maybe hinting at GEE approaches?
* Visualisations of cluster influences -> in pkg already begun
